# Commented out names are names already solved using Quickstart, need to re-add them if Quickstart is not active
# Double commented names are solved in Bargain, which shouldn't be tracked (for now)
from enum import StrEnum


class Character(StrEnum):
    # RobertWitterel= "Robert Witterel"
    # WilliamHoscut= "William Hoscut"
    EdwardNichols = "Edward Nichols"
    ## MartinPerrott= "Martin Perrott"
    JohnDavies = "John Davies"
    AlfredKlestil = "Alfred Klestil"
    CharlesMiner = "Charles Miner"
    HenryEvans = "Henry Evans"
    JamesWallace = "James Wallace"
    WinstonSmith = "Winston Smith"
    MarcusGibbs = "Marcus Gibbs"
    ThomasSefton = "Thomas Sefton"
    EmilOFarrell = "Emil O’Farrell"
    ChristianWolff = "Christian Wolff"
    OlusWiater = "Olus Wiater"
    DuncanMcKay = "Duncan McKay"
    FinleyDalton = "Finley Dalton"
    EdwardSpratt = "Edward Spratt"
    AbigailHoscutWitterel = "Abigail Hoscut Witterel"
    NunzioPasqua = "Nunzio Pasqua"
    EmilyJackson = "Emily Jackson"
    MsJaneBird = "Ms. Jane Bird"
    BunLanLim = "Bun-Lan Lim"
    ItBengSia = "It-Beng Sia"
    ChiohTan = "Chioh Tan"
    HokSengLau = "Hok-Seng Lau"
    ZungiSathi = "Zungi Sathi"
    ## FillipDahl= "Fillip Dahl"
    PaulMoss = "Paul Moss"
    SamuelGalligan = "Samuel Galligan"
    RoderickAndersen = "Roderick Andersen"
    DaveyJames = "Davey James"
    PeterMilroy = "Peter Milroy"
    ThomasLanke = "Thomas Lanke"
    CharlesHershtik = "Charles Hershtik"
    OmidGul = "Omid Gul"
    TimothyButement = "Timothy Butement"
    HuangLi = "Huang Li"
    JieZhang = "Jie Zhang"
    LiHong = "Li Hong"
    WeiLee = "Wei Lee"
    NicholasBotterill = "Nicholas Botterill"
    Maba = "Maba"
    # LewisWalker= "Lewis Walker"
    LeonidVolkov = "Leonid Volkov"
    AlarcusNikishin = "Alarcus Nikishin"
    AlekseiToporov = "Aleksei Toporov"
    NathanPeters = "Nathan Peters"
    LarsLinde = "Lars Linde"
    JohnNaples = "John Naples"
    RenfredRajub = "Renfred Rajub"
    AbrahamAkbar = "Abraham Akbar"
    WilliamWasim = "William Wasim"
    SolomanSyed = "Soloman Syed"
    HamadouDiom = "Hamadou Diom"
    # HenryBrennan= "Henry Brennan"
    AlexanderBooth = "Alexander Booth"
    PatrickOHagan = "Patrick O’Hagan"
    GeorgeShirley = "George Shirley"
    SamuelPeters = "Samuel Peters"
